AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unofficial-office-hours-skill

  Sample SAM Template for unofficial-office-hours-skill


Parameters:
  TranscribeVocabTerms:
    Type: String
    Default: alexa,apl,lowe,blankenburg,alexa-presentation-language
  TranscribeVocabName:
    Type: String
    Default: UnofficialOfficeHoursVocab

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  DataS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DataS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${DataS3Bucket}/*"
              - !Sub "arn:aws:s3:::${DataS3Bucket}"
            Condition:
              Bool:
                "aws:SecureTransport": "false"

  TranscribeStart:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transcribe-start/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          LOG_LEVEL: INFO
          TRANSCRIBE_VOCAB_NAME: !Ref TranscribeVocabName
      Policies:
        -
          Statement:
            -
              Sid: TranscribeStart
              Effect: Allow
              Action:
                - 'transcribe:StartTranscriptionJob'
              Resource: '*'
            -
              Sid: S3Access
              Effect: Allow
              Action:
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${DataS3Bucket}/*'
                - !Sub 'arn:aws:s3:::${DataS3Bucket}'

      Architectures:
        - x86_64


  TranscribeStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transcribe-status/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Policies:
        -
          Statement:
            -
              Sid: TranscribeStatus
              Effect: Allow
              Action:
                - 'transcribe:GetTranscriptionJob'
              Resource: '*'
      Architectures:
        - x86_64


  ComprehendParagraph:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: comprehend-paragraph/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 150
      Environment:
        Variables:
          LOG_LEVEL: INFO
          BUCKET_NAME: !Ref DataS3Bucket
      Policies:
        -
          Statement:
            -
              Sid: ComprehendCall
              Effect: Allow
              Action:
                - 'comprehend:DetectEntities'
                - 'comprehend:DetectKeyPhrases'
                - 'comprehend:BatchDetectEntities'
              Resource: '*'
            -
              Effect: Allow
              Action:   # TODO - figure out exactly what is needed
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${DataS3Bucket}/podcasts/*'
                - !Sub 'arn:aws:s3:::${DataS3Bucket}'
      Architectures:
        - x86_64

  ComprehendFullText:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: comprehend-fulltext/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 150
      Environment:
        Variables:
          LOG_LEVEL: INFO
          BUCKET_NAME: !Ref DataS3Bucket
      Policies:
        -
          Statement:
            -
              Sid: ComprehendCall
              Effect: Allow
              Action:
                - 'comprehend:DetectEntities'
                - 'comprehend:DetectKeyPhrases'
                - 'comprehend:BatchDetectEntities'
              Resource: '*'
            -
              Effect: Allow
              Action:   # TODO - figure out exactly what is needed
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${DataS3Bucket}/podcasts/*'
                - !Sub 'arn:aws:s3:::${DataS3Bucket}'
      Architectures:
        - x86_64

  PipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt PipelineStateMachineRole.Arn
      DefinitionString:
        !Sub
          - |-
            {
              "StartAt": "TranscribeStart",
              "States": {
                "TranscribeStart": {
                  "Type": "Task",
                  "Resource": "${TranscribeStartArn}",
                  "Next": "TranscribeWait"
                },
                "TranscribeWait": {
                  "Type": "Wait",
                  "Seconds": 30,
                  "Next": "TranscribeStatus"
                },
                "TranscribeStatus": {
                  "Type": "Task",
                  "Resource": "${TranscribeStatusArn}",
                  "Next": "IsTranscribeFinished"
                },
                "IsTranscribeFinished": {
                  "Type": "Choice",
                  "Default": "TranscribeWait",
                  "Choices": [
                    {
                      "Variable": "$.status",
                      "StringEquals": "FAILED",
                      "Next": "TranscribeFailed"
                    },
                    {
                      "Variable": "$.status",
                      "StringEquals": "COMPLETED",
                      "Next": "ComprehendParallel"
                    }
                  ]
                },
                "ComprehendParallel": {
                  "Type": "Parallel",
                  "Next": "End",
                  "Branches": [
                    {
                      "StartAt": "ComprehendParagraph",
                      "States": {
                          "ComprehendParagraph": {
                            "Type": "Task",
                            "Resource": "${ComprehendParagraphArn}",
                            "End": true
                          }
                      }
                    },
                    {
                      "StartAt": "ComprehendFullText",
                      "States": {
                          "ComprehendFullText": {
                            "Type": "Task",
                            "Resource": "${ComprehendFullTextArn}",
                            "End": true
                          }
                      }
                    }
                  ]
                },
                "End":{
                    "Type": "Pass",
                    "End": true
                },
                "TranscribeFailed": {
                  "Type": "Fail",
                  "Cause": "Transcription Failed.  Check CloudWatch logs for details.",
                  "Error": "ErrorA"
                }
              }
            }
          - {TranscribeStartArn: !GetAtt TranscribeStart.Arn, TranscribeStatusArn: !GetAtt TranscribeStatus.Arn, ComprehendParagraphArn: !GetAtt ComprehendParagraph.Arn, ComprehendFullTextArn: !GetAtt ComprehendFullText.Arn}



  PipelineStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "states.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource:
                  - !GetAtt TranscribeStart.Arn
                  - !GetAtt TranscribeStatus.Arn
                  - !GetAtt ComprehendParagraph.Arn
                  - !GetAtt ComprehendFullText.Arn



### Resources that run once

  CreateVocab:
    Type: Custom::LoadLambda
    Properties:
      ServiceToken: !GetAtt TranscribeVocabCreate.Arn
      CustomResourceAction: CreateVocab

  TranscribeVocabCreate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transcribe-vocab/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          LOG_LEVEL: INFO
          TRANSCRIBE_VOCAB_NAME: !Ref TranscribeVocabName
          TRANSCRIBE_VOCAB_TERMS: !Ref TranscribeVocabTerms
      Policies:
        -
          Statement:
            -
              Sid: TranscribeVocab
              Effect: Allow
              Action:
                - 'transcribe:CreateVocabulary'
                - 'transcribe:DeleteVocabulary'
              Resource: '*'
      Architectures:
        - x86_64



# Outputs:
